from tkinter import *
root = Tk()
root.geometry("200x200")
root.title("Things I like.")
list = Listbox(root, height = 10, width = 15, bg = "blue", fg = "lightblue", font = "Poppins")
lab = Label(root, text = "Things I Like")
list.insert(1, "Swimming")
list.insert(2, "Badminton")
list.insert(3, "Eating")
list.insert(4, "Sleeping")
list.insert(5, "Playing with my Elephant plushie")
list.insert(6, "Parents")
list.insert(7, "Friends")
list.insert(8, "School")
list.insert(9, "Riding on Highways")
list.insert(10, "Parties")
list.insert(11, "Coding")
list.insert(12, "Mathematics")
list.insert(13, "Sciences")
list.insert(14, "Dutch")
list.insert(15, "Etc.")
list.pack()
lab.pack()
root.mainloop()